/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.12.1/samples
 */

plugins {
    id("java")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.glassfish.jersey.containers:jersey-container-jdk-http:2.46")
    implementation("org.glassfish.jersey.inject:jersey-hk2:2.46")
    implementation("org.glassfish.jaxb:jaxb-runtime:2.3.6")
    implementation("org.glassfish.jaxb:txw2:2.3.6")
    implementation("com.sun.activation:jakarta.activation:1.2.2")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}
